### PR TITLE
Social and Donations Tests 

### PR DESCRIPTION
**Pull request by Jack-Austen**
Improved testing and made a minor change to add potential officials

### CODE REVIEW

**Review by Elliot-Lichtman — APPROVED** [review]
All tests pass, code does what it says it does!

**Comment by exoskeleton-1729** [comment]
All tests passed, code looks good! Coverage is improved.

**Comment by exoskeleton-1729** [comment]
All tests passed, code looks good! Coverage is improved.

**Review by exoskeleton-1729 — APPROVED** [review]
All tests passed, code looks good! Coverage is improved.

**Pull request merged**
