### PR TITLE
Emma Stake Updates

### PR DESCRIPTION
**Pull request by EmmaC24**
Added functionality to stake method and created a test that only tests stake

### CODE REVIEW

**Review by audreyyang25 — APPROVED** [review]
Looks good!

**Review by Jack-Austen — APPROVED** [review]
Works for me!

**Comment by Jack-Austen** [comment]
Works for me but has conflicts, so I think it would be better if Emma or someone else checks before committing to main

**Comment by avaweinrot** [comment]
ran tests and everything looks good! also looked over the file added and everything seems normal.

**Review by Jack-Austen — CHANGES_REQUESTED** [review]
Unresolved merge conflicts. Works with tests but have to fix!

**Review by naalahcohen — APPROVED** [review]

**Review by JoshuBao — APPROVED** [review]

**Comment by EmmaC24** [comment]
pushing to main

**Pull request merged**
