### PR TITLE
Combining Voting Tests

### PR DESCRIPTION
**Pull request by iwiener1**

### CODE REVIEW

**Review by Tyub23 — APPROVED** [review]
Good job

**Review by ABursting — CHANGES_REQUESTED** [review]
You have to fix the merge conflicts before I approve pull request (I think it should show them right below this comment), but other than that it looks good

**Review by ZachRossen — CHANGES_REQUESTED** [review]
Just some merge conflicts, but otherwise looks good

**Comment by iwiener1** [comment]
Merge conflicts should be fixed now

**Review by ABursting — APPROVED** [review]
looks good

**Pull request closed without merging**
