### PR TITLE
Finish Public Goods

### LINKED ISSUE #79: improve coverage for public goods contract

### PR DESCRIPTION
**Pull request by ericyoondotcom**
## Changes
- Made coverage entirely green (see screencaps)
- Added getters that will be required to make the website be able to list each public good

Screen Shot 2023-01-05 at 8 03 01 PM
Screen Shot 2023-01-05 at 8 03 06 PM

Fixed #79

### CODE REVIEW

**Comment by HarvardWestlake** [comment]
+1 this looks good, all tests passed on my machine!

**Review by Focus172 — APPROVED** [review]
Looks good!

**Comment by stevenk8819** [comment]
looks good! :)

**Comment by andrewtheiss** [comment]
Please use a hash or unique ID instead of a String[50].  NFT's only have a unique ID and contract address, i.e. https://testnets.opensea.io/assets/goerli/0x907b42eb0a146a78ed17a842828052c144f4b34e/33.  We should be using the #33 for the auction instead of the name of the NFT

**Pull request merged**
