### PR TITLE
Finish Dutch Auctions

### PR DESCRIPTION
**Pull request by ericyoondotcom**
Woohoo! I went ahead and implemented dutch auctions from scratch because it's easier than trying to convert Solidity code.

See all tests passing, and coverage is all green:
Screen Shot 2023-01-05 at 9 06 12 PM
Screen Shot 2023-01-05 at 9 06 18 PM

### CODE REVIEW

**Comment by Focus172** [comment]
+1 using asserts in internal methods is cringe and not even an attempt at a backdoor

**Review by Focus172 — APPROVED** [review]
Looks Good! :)

**Comment by Jack-Austen** [comment]
I tested it and it all works. Looked over the code and nothing seems wrong to me.

**Review by Jack-Austen — APPROVED** [review]
I tested it and it all works. Looked over the code and nothing seems wrong to me.

**Comment by Jack-Austen** [comment]
Eric asked for more reviewers since the code is so extensive, so I won't merge yet

**Comment by ericyoondotcom** [comment]
Thanks for reviews @Jack-Austen @Focus172 !

BTW Evan at all the places I've worked for they usually let the creator of the PR actually hit the merge button just in case there's something wrong FYI

**Pull request merged**
