### PR TITLE
fixed addNonTopics and removeNonTopics methods, increased coverage for tests for those 2 methods

### PR DESCRIPTION
**Pull request by KuroBean**
The overall Exclusivity testing average is still bad, but made fixes to the methods and testers I wrote. Can you look at the test coverages for addNonTopics and removeNonTopics (isInTopicsList is a method I used for testing those, which should also show up in the coverage thing)?

### CODE REVIEW

**Review by KKD2005 — APPROVED** [review]
All tests pass and removenontopics, is in topics list, and addnontopics methods all have pretty good coverage - a couple other methods inside exclusivity still have bad coverage but this pull request (to my understnading) only deals with the three methods listed above and those look good. everything looks good on my end!

**Review by audreyyang25 — CHANGES_REQUESTED** [review]
The exclusivity tests pass for me, but the community pot test fails -- could you update your branch before you merge

**Comment by audreyyang25** [comment]
> The exclusivity tests pass for me, but the community pot test fails -- could you update your branch before you merge

**Comment by audreyyang25** [comment]
> The exclusivity tests pass for me, but the community pot test fails -- could you update your branch before you merge

sorry actually ignore this -- I think there's something wrong with my computer

**Review by EmmaC24 — APPROVED** [review]
coverage is 100% for fixed methods and tests look good!

**Comment by audreyyang25** [comment]
> The exclusivity tests pass for me, but the community pot test fails -- could you update your branch before you merge

sorry actually ignore this

**Review by audreyyang25 — APPROVED** [review]

**Pull request merged**
