### PR TITLE
Merge branch 'code_SideQuestsScore' into CodeSideQuestsScore

### PR DESCRIPTION
**Pull request by elizakoblentz**
made a method in Side Quests that compares the high scores of the user to Mr. Theiss. Tested whether it compares or returns

### CODE REVIEW

**Review by Focus172 — CHANGES_REQUESTED** [review]
In the wise words of someone "stop using that ye ye old ass version and update your code already". Also merge changes from main into yours to have a larger test suite.

**Comment by Elliot-Lichtman** [comment]
+1
Tests working and does not break main.
The tests aren't exactly comprehensive but for now it's a good start.

**Review by Elliot-Lichtman — COMMENTED** [review]
Working code and tests! does not break main

**Review by Elliot-Lichtman — APPROVED** [review]

**Review by catherinecho — APPROVED** [review]
works for me. but you should merge to main??

**Pull request merged**
