### PR TITLE
Merge VotingAndRepersentation into main

### PR DESCRIPTION
**Pull request by Focus172**
## Implementing the finishVote() method.

> Allows votes to be closed in the way specified by the TechSpec. There are a large number of projects things that use voting a primary part and this puts voting in a state where it is *"ready"* to be interfaced with. There is an [issue](https://github.com/HarvardWestlake/Wolvercoin/blob/code_VotingAndRepresentation/contracts/VotingAndRep.vy#L155) on line 155 of votingAndRep.vy has been commented out for not working.

### CODE REVIEW

**Review by jmoreland57 — APPROVED** [review]
i approve. evan is a wonderful coder and its a pleasure to have him in my class

**Comment by elizakoblentz** [comment]
+1 i approve because of high coverage and i think it works

**Comment by elizakoblentz** [comment]
approve but close this time

**Review by elizakoblentz — APPROVED** [review]
it works

**Pull request merged**
