### PR TITLE
Simon code lotto

### PR DESCRIPTION
**Pull request by swacziarg**
Created tests for lottery function, coverage isnt 100%, but I couldn't find a way to 100% cover. Doesn't test the random picking of winners because it relies on time and sometimes the computer takes a little too long to run a function.

### CODE REVIEW

**Comment by avaweinrot** [comment]
test "simpleAuction.py" is failing. test for "lottery.py" passes but something is causing errors with the simpleAuction test. needs to be addressed.

**Review by avaweinrot — CHANGES_REQUESTED** [review]
see other comment about simpleAuction.py tests failing when I run brownie test with the simon code lotto checked out.

**Review by iwiener1 — CHANGES_REQUESTED** [review]
There was an error at setup of test_bid.

**Comment by swacziarg** [comment]
Made a new branch because of issues with testing

**Pull request closed without merging**
